### ISSUE TITLE
Broken Jmol example

### ISSUE THREAD

**Issue by jamesscottbrown** [MolQL/molql#1]
The MolQL [front page](http://molql.org/) gives an example Jmol query ``substructure = helix``

However, in the [MolQL Explorer](http://molql.org/explorer.html) this gives the error message

> Error: values must be part of an comparison, value 'structure'

However, ``substructure = "helix"`` *does* work. The help panel to the right suggests that this is expected:

> like structure, the value of this parameter depends upon the context. Used with select substructure=x, x can be either the **quoted keyword** "none", "turn", "sheet", "helix", "dna", "rna", "carbohydrate", "helix310", "helixalpha", or "helixpi", or the respective number 0-9. In the context {}.substructure, the return value is a number; in the context label %[substructure], the return is one of the nine keywords.*

**Comment by dsehnal** [comment]
Thanks, changed it to just "helix" without the "substructure = " part.
