### ISSUE TITLE
"x.toLowerCase is not a function" error for some queries

### ISSUE THREAD

**Issue by jamesscottbrown** [MolQL/molql#2]
In the [MolQL explorer](http://molql.org/explorer.html), the Jmol query ``substructure = 1`` gives the error message

> TypeError: x.toLowerCase is not a function. (In 'x.toLowerCase()', 'x.toLowerCase' is undefined)

**Comment by arose** [comment]
fixed, `substructure = 1` works now, tahnks for reporting!
