### ISSUE TITLE
download dosen't work

### ISSUE THREAD

**Issue by luckyxutao** [MolQL/molql#5]
<img width="698" alt="image" src="https://github.com/MolQL/molql/assets/1294316/6e33a1a5-08d2-4b8d-aafa-94e7231a3da1">
<img width="1196" alt="image" src="https://github.com/MolQL/molql/assets/1294316/9045c475-15f2-46fb-9856-6702cf5aafd2">

thank you very much for you help

**Comment by dsehnal** [comment]
Hi, we were moving the webchem server to a new machine and didn't spin up the CoordinateServer there anymore. I will update this.

**Comment by dsehnal** [comment]
Should be fixed
